# Generated by Django 5.0 on 2023-12-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ttable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='utable',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
