# Generated by Django 5.0 on 2023-12-13 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_delete_utable'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='ttable',
        ),
        migrations.AddField(
            model_name='task_table',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.user_table'),
        ),
    ]
