# Generated by Django 5.0 on 2023-12-15 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_table_username_delete_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_table',
            old_name='username',
            new_name='userid',
        ),
    ]
