# Generated by Django 5.0 on 2023-12-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_rename_username_task_table_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_table',
            old_name='userid',
            new_name='username',
        ),
    ]
